### ISSUE TITLE
[BUG] 처음 로그인 후, Home 화면으로 전환 불가능

### ISSUE THREAD

**Issue by gee2450** [kookmin-sw/capstone-2024-18#26]
### 파트
- FE

### TODO
- [x] 로그인 후, Home 화면으로 갔다가, 다시 로그인 화면으로 무한으로 돌아옴
  - accessToken이 저장된 것이 바로 AuthContext의 accessToken, refreshToken에 반영이 안됨

**Comment by nanana3679** [comment]
@gee2450 버그 수정하여 fe에 푸쉬했습니다.
